### ISSUE TITLE
缺少桶参数

### ISSUE THREAD

**Issue by LiuDanK** [Galen-Yip/tencent-cloud-cos-upload-image#1]
我配置完之后点击上传提示缺少桶参数?可以帮我看一下我的配置有何问题吗?
![image](https://user-images.githubusercontent.com/32576900/57188166-9a54be80-6f2c-11e9-9281-bfee1bc6c06e.png)

**Comment by Galen-Yip** [comment]
你这里要提供一下你的appid，要不你直接加我wx看看，wx: 275497985

**Comment by LiuDanK** [comment]
> 你这里要提供一下你的appid，要不你直接加我wx看看，wx: 275497985

这块的我现在没有用腾讯云的了,改成七牛云了
